/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dxi.server;

import org.junit.Test;
import java.io.IOException;

public class AppTest {
    @Test
    public void web3jHasSameAccountsAsGanache() throws IOException {
        App classUnderTest = new App();
    }
}
