/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dxi.server;

import org.junit.Test;

public class AppTest {
    @Test
    public void appCanBeInstantiated() {
        App app = new App();
    }
}